config/routes.rb
Rails.application.routes.draw do
  get 'stimulus/dictionary'
  devise_for :users

  root to: "pages#home"
  resources :lists do
    resources :reviews, only: [:new, :create, :index]
    resources :products, only: [:new, :create, :edit, :update, :destroy]
    resources :list_guests, only: [:new, :create, :destroy] do
      collection do
        get 'check_guest'
      end
    end
  end
  resources :reviews, only: [:show, :destroy]
  post '/lists/new' => 'lists#create'
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :tag
  belongs_to :user
  belongs_to :supermarket, optional: true
  has_many :products, dependent: :destroy
  has_many :list_guests, dependent: :destroy
  has_many :reviews, dependent: :destroy

  ACCESS_TYPES = ["Public", "Private"]


  def average_rating
    reviews.any? ? reviews.average(:rating).to_f : 0
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  include BudgetHelper
  helper_method :compare_budget

  def index
    session[:chosen_colors] ||= []
    @lists = List.all
    session[:chosen_colors] << @color
  end

  def show
    @list = List.find(params[:id])
    @review = Review.new
    @list_guest = @list.list_guests.new
    @list_guests = @list.list_guests.includes(:user)
  end

  def new
    @list = List.new
  end

  def edit
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    Rails.logger.info(@list.inspect)  # Log the list attributes before save
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  def reviews
    @list = List.find(params[:id])
    @reviews = @list.reviews
  end

  private

  def list_params
    params.require(:list).permit(:name, :access_type, :budget, :tag_id)
  end
end

app/views/lists/edit.html.erb
<div class="edit-list">
  <div class="card main-card-rounded w-100" style="border-style: none">
    <div class="row mb-4 mt-3">
      <div class="col-2 center-icon px-1 pt-1">
        <%= link_to list_path(@list) do %><i class="fa-solid fa-circle-chevron-left fa-xl" style="color: #7c5bae;"></i>
        <% end %>
      </div>
      <div class="col-8 pt-1 px-8">
        <h1 style='text-align: left; font-size: 18px; margin-bottom: 1px'><strong>Edit your list</strong></h1>
      </div>
      <div class="col-2 center-icon px-1 pt-1">
      </div>
    </div>

    <div class="card-body">
      <%= simple_form_for @list, url: list_path(@list), method: :patch, remote: true do |form| %>
        <div class="field">
          <%= form.input :name %>
        </div>

        <div class="field">
          <%= form.input :budget, label: "Budget" %>
        </div>

        <div class="field">
          <%= form.input :tag_id, label: "Tag", collection: Tag.all %>
        </div>

        <div class="actions new-btn mt-3">
          <%= form.submit %>
        </div>
      <% end %>

      <% if @list.errors.any? %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="add-container">

  <div class="mylists-container">
    <div class="card main-card-rounded w-100" style="border-style: none">

      <div class="card-body">
        <!--USERNAME + ADD LIST ICON SECTION-->
        <div class="row mb-3 mt-3">
          <div class="col-10">
            <h1 style='text-align: left; font-size: 28px;'>Hello, <strong><%= current_user.first_name %>!</strong></h1>
          </div>
          <div class="col-2 center-icon px-1 pt-1">
            <%= link_to new_list_path do %>
              <i class="fa-solid fa-plus fa-xl" style="color: #7c5bae;"></i>
            <% end %>
          </div>
        </div>

        <!--LIST CARDS WITH DIFFERENT COLORS-->
        <% if @lists.any? %>
        <div class="mylists-grid-container">
          <% cont = 0 %>
          <% @lists.each_slice(2).with_index do |listas, listas_index| %>
            <% cont += 1 %>
            <% minimalistic_colors = [
              "#E57373", "#F06292", "#BA68C8", "#9575CD", "#7986CB",  # Reds and Purples
              "#4FC3F7", "#4DB6AC", "#81C784",  # Blues, Greens, and Yellows
              "#FFD54F", "#FFB74D", "#FF8A65", "#A1887F", "#90A4AE",  # Oranges, Browns, and Grays
              "#F48FB1", "#CE93D8", "#B39DDB", "#9FA8DA", "#90CAF9", "#FFD54F", "#FFB74D", "#FF8A65", "#A1887F", "#90A4AE"  # Orange, Violet, Teal
            ] %>
            <div class="row px-3 py-1">
              <% listas.each_with_index do |list, index| %>
                <div class="col-6">
                  <button class="list-button list-button-text" style="background-color: <%= minimalistic_colors[(listas_index * 2 + index) % minimalistic_colors.size] %>">
                    <%= link_to list.name, list_path(list), class: "list-button-text" %>
                    <% if list.tag %>
                      <%= link_to list_path(list) do %>
                      <i class="fa-solid fa-<%= list.tag.image %> list-icon" style= "color:#ffffff "></i>
                      <% end %>
                    <% else %>
                        <i class="fa-solid fa-gift list-icon" style="color: #ffffff;"></i>
                     <% end %>

                  </button>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
        <% else %>
          <div class="no-lists-message" style="text-align: center; margin-top: 50px;">
            <h2>No lists available</h2>
            <%= image_tag 'captura.png', alt: 'No lists available', style: 'max-width: 100%; height: auto;' %>
            <p>Start by creating a new list using the plus icon above.</p>
          </div>
        <% end %>
      </div>

    </div>
  </div>

</div>

app/views/lists/new.html.erb
<div class="new-list">
  <div class="card main-card-rounded w-100" style="border-style: none">
    <div class="row mb-4 mt-3">
      <div class="col-2 center-icon px-1 pt-1">
        <%= link_to lists_path do %><i class="fa-solid fa-circle-chevron-left fa-xl" style="color: #7c5bae;"></i>
        <% end %>
      </div>
      <div class="col-8 pt-1 px-8">
        <h1 style='text-align: left; font-size: 18px; margin-bottom: 1px'><strong>New list</strong></h1>
      </div>
      <div class="col-2 center-icon px-1 pt-1">
      </div>
    </div>

    <div class="card-body">
      <%= simple_form_for @list, url: new_list_path, remote: true do |form| %>
        <div class="field">
          <%= form.input :name %>
        </div>

        <div class="field">
          <%= form.input :budget, label: "Budget" %>
        </div>

        <div class="field">
          <%= form.input :tag_id, label: "Tag", collection: Tag.all %>
        </div>

        <div class="actions new-btn mt-3">
          <%= form.submit %>
        </div>
      <% end %>

      <% if @list.errors.any? %>
    <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="show-container">
  <div class="show-list-container">
    <div class="card main-card-rounded w-100" style="border-style: none">

      <div class="card-body">

        <!--TOP MENU NAVBAR-->
        <div class="row mb-3 mt-3">
          <div class="col-2 center-icon px-1 pt-1">
            <%= link_to lists_path do %><i class="fa-solid fa-circle-chevron-left fa-xl" style="color: #7c5bae;"></i>
            <% end %>
          </div>
          <div class="col-6 pt-1 px-8">
            <h1 style='text-align: left; font-size: 18px;'><strong> <%= @list.name %> </strong></h1>
          </div>
          <div class="col-1 center-icon px-1 pt-1">
              <%= link_to edit_list_path do %><i class="fa-solid fa-pen-to-square" style="color: #7c5bae;"></i>
              <% end %>
          </div>
          <!--ADD A NEW PRODUCT-->
          <div class="col-1 center-icon px-1 pt-1">
            <%=render 'shared/search_user' %>
          </div>
          <div class="col-1 center-icon px-1 pt-1">
            <%= link_to list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %><i class="fa-solid fa-trash" style="color: #da0b20;"></i><% end %>
          </div>
        </div>

        <!--INVITED GUESTS SECTION-->
        <% if @list_guests.any? %>
          <div class="row m-3">
            <div class="col-12">
              <div class="row">
                <div class="col-10 mt-2">
                  <h1 style="text-align: left; font-size: 15px;"><strong>Guests</strong></h1>
                </div>
              </div>
              <div class="row">
                <%= render partial: 'shared/list_guest', collection: @list_guests, as: :list_guest, locals: { list: @list } %>
              </div>
            </div>
          </div>
        <% end %>

        <!--BUDGET SECTION AND LIST CREATION DATE-->
        <div class="row mb-3 mt-5">
          <div class="col-12" style="text-align: center">
            <p style="font-size: 10px">Created at <%= @list.created_at.strftime("%B %d, %Y %H:%M") %></p>
            <h2 style="font-size: 15px">Total budget</h2>
            <h1 style="font-size: 30px"><strong>$<%= @list.budget %></strong><h1>
          </div>
        </div>

        <!--BUDGET SPENDING PROGRESS BAR-->
        <div class="row m-3">
          <div class="col-12 card budget-card-bg">
            <div class="row">
              <div class="col-6"><p id="titles"><i class="fa-solid fa-circle fa-sm" style="color: #1edd88;"></i> Left to spend</p></div>
              <div class="col-6"><p id="titles"><i class="fa-solid fa-circle fa-sm" style="color: #0d6efd;"></i> Budget spent</p></div>
            </div>
            <div class="row">
              <div class="col-6"><p id="amounts">$<span id='element-left-spent-amount' data-total-left-spent-amount="<%= left_to_spend(@list.budget, list_price_sum(@list.products)) %>"><%= left_to_spend(@list.budget, list_price_sum(@list.products)) %></span></p></div>
              <div class="col-6"><p id="spent_amounts">$<span id='element-spent-amount' data-total-spent-amount="<%= @list.spent %>"><%= @list.spent %></span></p></div>
            </div>
            <div class="row">
              <div class="col-12 mb-4">
                <% if surpass_budget(list_price_sum(@list.products), @list.budget) == false %>
                  <div class="progress" style="">
                    <!--BUDGET SPENT-->
                    <div class="progress-bar" role="progressbar" style="width:<%= spent_percentage(list_price_sum(@list.products), @list.budget) %>%;" aria-valuenow="<%= spent_percentage(list_price_sum(@list.products), @list.budget) %>" aria-valuemin="0" aria-valuemax="100">
                    </div>
                    <!--REMAINING BUDGET TO SPEND-->
                    <div class="progress-bar bg-success" role="progressbar" style="width:<%= remaining_budget_percentage(left_to_spend(@list.budget, list_price_sum(@list.products)), @list.budget)%>%;" aria-valuenow="<%= remaining_budget_percentage(left_to_spend(@list.budget, list_price_sum(@list.products)), @list.budget)%>" aria-valuemin="0" aria-valuemax="100">
                    </div>
                  </div>
                <% else %>
                  <div class="progress" style="">
                    <!--BUDGET SPENT-->
                    <div class="progress-bar bg-danger" role="progressbar" style="width:<%= spent_percentage(list_price_sum(@list.products), @list.budget) %>%;" aria-valuenow="<%= spent_percentage(list_price_sum(@list.products), @list.budget) %>" aria-valuemin="0" aria-valuemax="100">
                    </div>
                    <!--REMAINING BUDGET TO SPEND-->
                    <div class="progress-bar bg-danger" role="progressbar" style="width:<%= remaining_budget_percentage(left_to_spend(@list.budget, list_price_sum(@list.products)), @list.budget)%>%;" aria-valuenow="<%= remaining_budget_percentage(left_to_spend(@list.budget, list_price_sum(@list.products)), @list.budget)%>" aria-valuemin="0" aria-valuemax="100">
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <!--PRODUCT LIST SECTION-->
        <div class="row m-3 mb-5">
          <div class="col-10 mt-2"><h1 style="text-align: left; font-size: 15px"><strong>Item List</strong></h1></div>
          <div class="col-2 mt-2"><%= render 'shared/search_products' %></div>
          <% if @list.products.empty? %>
          <div class="col-12 card budget-card-bg">
            <div style="text-align: center" class="my-3">
              <img src="<%=image_url("empty_list.png")%>" alt="No products yet" style="width: 225px; height: 225px" class="no-item-center-image mb-3"/>
              <h1><strong>Empty List</strong></h1>
              <p style="font-size: 15px" class="px-3">Your shopping list is currently empty. Feel free to add products to your list.</p>
            </div>
          </div>
          <% else %>
            <div id="products">
              <% sorted_list = @list.products.order(:created_at) %>
              <% sorted_list.each do |product| %>
                <%= render "products/product", product: product %>
              <% end %>
            </div>
          <% end %>
          <%= link_to 'View Reviews', list_reviews_path(@list),  class:"violet-button mt-3"%>
        </div>

      </div>

    </div>
  </div>
  <%= render 'shared/search_products' %>
</div>


<script>
  var totalSpent = parseInt(document.querySelector('#element-spent-amount').dataset.totalSpentAmount, 10);
  var totalLeftSpent = parseInt(document.querySelector('#element-left-spent-amount').dataset.totalLeftSpentAmount, 10);


  document.querySelectorAll(".product-checkbox").forEach(function(checkbox) {
    checkbox.addEventListener("change", function() {
      const productId = this.dataset.productId;
      const checked = this.checked;
      const productPrice = parseInt(this.dataset.productPrice, 10);
      console.log(productPrice)
      const url = `/lists/<%= @list.id %>/products/${productId}`;

      fetch(url, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').content
        },
        body: JSON.stringify({ product: { checked: checked, list_id: '<%= @list.id %>' } })
      })
        .then(response => response.json())
        .then(data => {
          if (data.status === 'ok') {
            console.log(`Product ${checked ? 'checked' : 'unchecked'} successfully`);
            if (checked) {
              totalSpent += productPrice;
              totalLeftSpent -= productPrice;
            } else {
              totalSpent -= productPrice;
              totalLeftSpent += productPrice;
            }
            document.querySelector('#element-spent-amount').innerHTML = `${totalSpent}`;
            document.querySelector('#element-left-spent-amount').innerHTML = `${totalLeftSpent}`;
          } else {
            console.error("Failed to update product");
          }
        })
        .catch(error => console.error("Error:", error));
    });
  });
</script>