config/routes.rb
Rails.application.routes.draw do
  get 'stimulus/dictionary'
  devise_for :users

  root to: "pages#home"
  resources :lists do
    resources :reviews, only: [:new, :create, :index]
    resources :products, only: [:new, :create, :edit, :update, :destroy]
    resources :list_guests, only: [:new, :create, :destroy] do
      collection do
        get 'check_guest'
      end
    end
  end
  resources :reviews, only: [:show, :destroy]
  post '/lists/new' => 'lists#create'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :list
  validates :name, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @list = List.find(params[:list_id])
  end

  def edit
    @product = Product.find(params[:id])
    @list = List.find(params[:list_id])
  end

  def create
    @product = Product.new(product_params)
    @list = List.find(params[:list_id])
    @product.quantity = 1
    @product.price = 0
    @product.list = @list
    if @product.save
      flash[:notice] = 'Product added'
      respond_to do|format|
        format.html {redirect_to list_path(@list), notice: 'Product was successfully created.'}
        format.turbo_stream

      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @product = Product.find(params[:id].to_i)
    @list = List.find(params[:list_id].to_i) || List.find(params[:product][:list_id].to_i)
    @product.list = @list

    new_checked = params[:product][:checked]

    if @product.checked != params[:product][:checked]
      if new_checked
        @list.spent += @product.price
      elsif !new_checked && @list.spent > 0
        @list.spent -= @product.price
      end
    end

    if @product.update(product_params)
      @list.save
      respond_to do |format|
        format.json { render json: { status: :ok } }
        format.html { redirect_to @product.list }
      end
    else
      render "lists/show", status: :unprocessable_entity, alert: flash[:alert] = "Product not updated!"
    end
  end

    def destroy
      @list = List.find(params[:list_id])
      @product = @list.products.find(params[:id])
      @product.destroy
      redirect_to @list, status: :see_other, notice: 'Product was successfully deleted.'
    end

    private
    def product_params
        params.require(:product).permit(:name, :brand, :quantity, :price, :checked, :list_id)
    end

end

app/views/products/_product.html.erb
<div class="col-12 card budget-card-bg">
  <div class="row g-0 m-3">
    <div class="col-2">
      <input type="checkbox"
             name="product-<%= product.id %>"
             id="product-<%= product.id %>"
             class="form-check-input me-1 product-checkbox"
             data-product-id="<%= product.id %>"
             data-product-price="<%= product.price %>"
             <%= 'checked' if product.checked %>>
    </div>
    <div class="col-8" style="text-align: left"><%= product.name %></div>
    <div class="col-2" style="text-align: right">
      <%= link_to edit_list_product_path(@list, product) do %>
        <i class="fa-solid fa-ellipsis fa-xl" style="color: #7c5bae"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/products/create.turbo_stream.erb
<%= turbo_stream.append "products", partial: "products/product", locals: { product: @product } %>
<%= turbo_stream.replace "product_name" do %>

      <input name="product[name]"
            class="form-control"
            placeholder="enter product"
              data-dictionary-target= "input"
              data-action ="keyup->dictionary#update"
              id="product_name"
          >
    <% end %>

app/views/products/edit.html.erb
<div class="add-container">
  <div class="card main-card-rounded w-100" style="border-style: none">
    <div class="row mb-4 mt-3">
      <div class="col-2 center-icon px-1 pt-1">
        <%= link_to list_path(@list) do %><i class="fa-solid fa-circle-chevron-left fa-xl" style="color: #7c5bae;"></i>
        <% end %>
      </div>
      <div class="col-8 pt-1 px-8">
          <h1 style='text-align: left; font-size: 18px; margin-bottom: 1px'><strong>Edit Product</strong></h1>
          </div>
      <div class="col-2 center-icon px-1 pt-1">
        <%= link_to list_product_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %><i class="fa-solid fa-trash" style="color: #da0b20;"></i>
        <% end %>
      </div>
    </div>

    <div class="card-body">
      <%= simple_form_for [@list, @product] do |f| %>
        <div class="mb-3">
          <%= f.input :name, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.input :price, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.input :quantity, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.input :brand, class: "form-control" %>
        </div>
        <div class="violet-button">
          <%= f.button :submit, "Update Product", class: 'violet-button', style: 'font-size:16px' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<%= simple_form_for @product, url: list_products_path(@list.id), method: :post do |form| %>
  <div class="container">
    <div class="card shadow-sm">
      <div class="card-body">
        <div class="mb-3">
          <%= form.input :name, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.input :price, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.input :quantity, class: "form-control" %>
        </div>
        <div class="d-flex">
          <%= link_to 'Back', list_path(@list), class: "btn btn-secondary me-auto" %>  <%= form.button :submit, "Add Product", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>