config/routes.rb
Rails.application.routes.draw do
  get 'stimulus/dictionary'
  devise_for :users

  root to: "pages#home"
  resources :lists do
    resources :reviews, only: [:new, :create, :index]
    resources :products, only: [:new, :create, :edit, :update, :destroy]
    resources :list_guests, only: [:new, :create, :destroy] do
      collection do
        get 'check_guest'
      end
    end
  end
  resources :reviews, only: [:show, :destroy]
  post '/lists/new' => 'lists#create'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :set_list, only: %i[new create index]

  def index
    @reviews = Review.where(list_id: params[:list_id])
    @review = Review.new
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @list = List.find(params[:list_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.list_id = @list.id
    @review.user = current_user
    if @review.save
      redirect_to list_reviews_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/views/reviews/index.html.erb
<div class="reviews-container">
<!--MAIN CARD THAT CONTAINS ALL REVIEWS-->

  <div class="myreviews-container">
    <div class="card main-card-rounded w-100" style="border-style: none; overflow: auto; height: 1000px">
      <!---->
      <div class="card-body">
        <!--ROW THAT CONTAINS BACK BUTTON WITH LIST TITLE-->
        <div class="row">
          <div class="col-2">
            <%= link_to list_path(@list) do %><i class="fa-solid fa-circle-chevron-left fa-xl" style="color: #7c5bae;"></i><% end %>
          </div>
          <div class="col-10 px-1">
            <p class="card-title"><strong><%= @list.name %></strong></p>
          </div>
        </div>

        <!--METHOD THAT WILL CHECK IF REVIEWS EXIST OR NOT-->
        <% if @reviews.empty?  %>
        <div style="text-align: center" class="mt-5">
          <img src="<%=image_url("add_reviews.png")%>" alt="No reviews yet" style="width: 225px; height: 225px" class="no-item-center-image"/>
          <h1><strong>No reviews yet</strong></h1>
          <p style="font-size: 15px" class="px-3">There are currently no reviews for this list. Feel free to add one and share your experience!</p>
        </div>
        <!--LIST OF REVIEWS, IF REVIEW ARRAY IS NOT EMPTY-->
        <% else %>
          <div class="overall-card-bg mb-3">
            <div class="card-body" style="background-color: rgb(213, 210, 210); border-radius: 15px; border-color: rgb(213, 210, 210)">
            <div class="row">
              <div class="col-7 p-1">
                <div class="row g-0">
                  <div class='col-4 mr-1'>
                    <%= 5 %> <i class="fa-solid fa-star" style="color: #b89c01;"></i>
                  </div>
                  <div class='col-8 ml-0'>
                    <div class="progress rounded">
                      <div class="progress-bar rounded" role="progressbar" style="width: <%= progress(fivestar(@list.reviews)) %>%;" aria-valuenow="<%= fivestar(@list.reviews) %>" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                </div>
                <div class="row g-0">
                  <div class='col-4 mr-1'>
                    <%= 4 %> <i class="fa-solid fa-star" style="color: #b89c01;"></i>
                  </div>
                  <div class='col-8 ml-0'>
                    <div class="progress rounded">
                      <div class="progress-bar rounded" role="progressbar" style="width: <%= progress(fourstar(@list.reviews)) %>%;" aria-valuenow="<%= fourstar(@list.reviews) %>" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                </div>
                <div class="row g-0">
                  <div class='col-4 mr-1'>
                    <%= 3 %> <i class="fa-solid fa-star" style="color: #b89c01;"></i>
                  </div>
                  <div class='col-8 ml-0'>
                    <div class="progress rounded">
                      <div class="progress-bar rounded" role="progressbar" style="width: <%= progress(threestar(@list.reviews)) %>%;" aria-valuenow="<%= threestar(@list.reviews) %>" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                </div>
                <div class="row g-0">
                  <div class='col-4 mr-1'>
                    <%= 2 %> <i class="fa-solid fa-star" style="color: #b89c01;"></i>
                  </div>
                  <div class='col-8 ml-0'>
                    <div class="progress rounded">
                      <div class="progress-bar rounded" role="progressbar" style="width: <%= progress(twostar(@list.reviews)) %>%;" aria-valuenow="<%= twostar(@list.reviews) %>" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                </div>
                <div class="row g-0">
                  <div class='col-4 mr-1'>
                    <%= 1 %> <i class="fa-solid fa-star" style="color: #b89c01;"></i>
                  </div>
                  <div class='col-8 ml-0'>
                    <div class="progress rounded">
                      <div class="progress-bar rounded" role="progressbar" style="width: <%= progress(onestar(@list.reviews)) %>%;" aria-valuenow="<%= onestar(@list.reviews) %>" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                </div>
              </div>
              <div class='col-5 ml-2'>
                <h1 style="font-size: 30px; text-align: right" class="m-0" style="align-items: right;"><strong><%= @list.average_rating %></strong></h1>
                <div class="star-rating-container m-0">
                  <% rating = @list.average_rating %>
                  <% full_stars = rating.floor %>
                  <% half_star = (rating - full_stars >= 0.5) ? 1 : 0 %>
                  <% empty_stars = 5 - full_stars - half_star %>

                  <% full_stars.times do %>
                    <span class="star full-star"></span>
                  <% end %>

                  <% if half_star == 1 %>
                    <span class="star half-star"></span>
                  <% end %>

                  <% empty_stars.times do %>
                    <span class="star empty-star"></span>
                  <% end %>
                </div>
                <p style="font-size: 13px; text-align: right"><small class="text-muted">Based on <%= @list.reviews.count %> Reviews </small></p>
              </div>
            </div>
            </div>
          </div>

          <% @reviews.each do |review| %>
            <div class="row no-gutters">
              <div class="row no-gutters">
                <div class="col-3 d-flex align-items-center justify-content-center p-0 m-0">
                  <a href="#" class="img-fluid rounded-circle avatar-reviews-img">
                    <% if current_user.photo.present?  %>
                      <%= cl_image_tag current_user.photo.key, class: "img-fluid rounded-circle avatar-reviews-img", alt: "" %>
                    <% else  %>
                      <%= image_tag "user-logo.png", class: "img-fluid rounded-circle avatar-reviews-img", alt: "" %>
                    <% end %>
                  </a>
                </div>
                <div class="col-9 p-2 ml-1">
                  <p class="card-title mb-0"><strong><%= review.user.first_name %> <%= review.user.last_name %></strong></p>
                  <p class="card-text"><small class="text-muted"><%= review.created_at.strftime("%B %d, %Y %H:%M") %></small></p>
                </div>
              </div>
              <div class="row no-gutters">
                <div class="col-12">
                  <div class="card-body p-2">
                    <div class="star-rating-review-container mb-2">
                      <% rating = review.rating %>
                      <% full_stars = rating.floor %>
                      <% half_star = (rating - full_stars >= 0.5) ? 1 : 0 %>
                      <% empty_stars = 5 - full_stars - half_star %>

                      <% full_stars.times do %>
                        <span class="star-review-card full-star"></span>
                      <% end %>

                      <% if half_star == 1 %>
                        <span class="star-review-card half-star"></span>
                      <% end %>

                      <% empty_stars.times do %>
                        <span class="star-review-card empty-star"></span>
                      <% end %>
                    </div>
                    <p class="card-text"><%= review.comment %></p>
                  </div>
                </div>
              </div>
            </div>
            <!--METODO QUE LE COLOCA UNA LINEA ESPACIADORA A TODOS LOS REVIEWS CON EXCEPCION AL ULTIMO-->
            <% if review != @reviews.last %>
              <hr>
            <% end %>
          <% end %>
        <% end %>
        <div class="button-container">
          <button type="button" class="violet-button mt-3" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Review</button>
        </div>

      </div>
    </div>
  </div>

</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Rate this list</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= simple_form_for [@list, @review], url: list_reviews_path(@list) do |f| %>
            <%= f.input :comment, label: 'Comment:' %>
            <%= f.input :rating, collection: (1..5).to_a, input_html: {data: {controller: "star-rating"}} %>
          <div class="d-grid gap-2 d-md-block">
            <%= f.button :submit, "Post Review", class: 'rounded-button mt-3', style: 'font-size: 16px; height: 50px; width: 100%; border-radius: 40px'%>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/reviews/new.html.erb
<div class="container shadow border p-3 mt-5">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <!-- This div is centered and takes 6 columns -->
      <%= simple_form_for [@list, @review], url: list_reviews_path do |f| %>
        <%= f.input :comment, label: 'Comment:' %>
        <%= f.input :rating, label: 'How do you rate this list?', collection: 0..5, prompt: "Provide a rating" %>
        <div class="d-grid gap-2 d-md-block">
          <%= f.button :submit, "Post Review", class: 'violet-button'%>
          <%= link_to 'Back', list_path(id: @list.id), class:'btn btn-outline-primary m-3'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<h2>This is the show view</h2>